FROM node:18.13-alpine as builder

ARG NODE_ENV=build
ENV NODE_ENV=${NODE_ENV}

COPY ["package*.json", "yarn.lock", "./"]

RUN yarn install

COPY . .

RUN yarn build

USER node
WORKDIR /usr/src/app


EXPOSE 8085
ENTRYPOINT ["yarn", "start:dev"]