version: '3.7'

services:
  mongo:
    image: mongo:5.0
    container_name: local-mongo
    restart: always
    ports:
      - '27033:27017'
    environment:
      TZ: UTC
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: test_db
    #logging:
    #  driver: none
    #volumes:
    #  - ./.mongo_data:/data/db


  mysql:
    image: arm64v8/mysql
    container_name: local-mysql
    restart: always
    ports:
      - '3316:3306'
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my_db
      MYSQL_PASSWORD: 123456
      #MYSQL_USER: root
    #volumes:
    #  - ./.mysql-data/db:/var/lib/mysql


  redis:
    image: redis:6.2-alpine
    container_name: local-redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      TZ: UTC
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
      REDIS_HOST: cache
      #REDIS_USERNAME: default
    command: ["redis-server", "--appendonly", "yes", "--requirepass","123456"]
    #logging:
    #  driver: none
    #volumes:
    #  - ./.redis_data:/data

  seed-v0.0.1:
    container_name: seed_basic
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
  